import { callVertexAiApi } from './vertex-ai-openHandle';

describe('Test Vertex AI OpenHandle, The issue comes from the length of the answer given by the model', () => {
  // Change projectID to your project ID
  const projectId = '';
  it('Working Short prompt, should call and receive response from Vertex AI', async () => {
    const response = await callVertexAiApi(
      projectId,
      'Hello what is the capital of paris ?',
    );
    console.log(response);
    expect(response).toBeDefined();
  }, 40000);
  it('Working long prompt, short response, should call and receive response from Vertex AI', async () => {
    const prompt = `\`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel turpis nunc eget lorem dolor sed. Dolor sit amet consectetur adipiscing elit ut. Eget sit amet tellus cras adipiscing enim eu turpis egestas. Aliquet nec ullamcorper sit amet risus. Id semper risus in hendrerit gravida rutrum quisque non tellus. Nisl suscipit adipiscing bibendum est ultricies integer. Accumsan in nisl nisi scelerisque eu ultrices vitae. Sit amet nisl suscipit adipiscing bibendum est ultricies integer quis. Etiam tempor orci eu lobortis elementum nibh. Aenean euismod elementum nisi quis eleifend.

Potenti nullam ac tortor vitae. Vel pretium lectus quam id. Adipiscing tristique risus nec feugiat. Adipiscing diam donec adipiscing tristique risus nec feugiat in. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Feugiat vivamus at augue eget arcu dictum. Tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque. In aliquam sem fringilla ut morbi tincidunt augue. Porta nibh venenatis cras sed felis. Aliquam malesuada bibendum arcu vitae. A cras semper auctor neque vitae tempus quam. Sit amet dictum sit amet justo donec enim diam vulputate. Volutpat sed cras ornare arcu dui vivamus arcu. Sed odio morbi quis commodo odio aenean sed.

Neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Sit amet aliquam id diam maecenas ultricies. Volutpat maecenas volutpat blandit aliquam. In pellentesque massa placerat duis ultricies lacus sed turpis. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Aliquam purus sit amet luctus venenatis. Enim tortor at auctor urna nunc. Elementum sagittis vitae et leo duis ut. Lacus vestibulum sed arcu non odio euismod lacinia at. Quam vulputate dignissim suspendisse in est. Magnis dis parturient montes nascetur. Quis imperdiet massa tincidunt nunc pulvinar.

Adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Malesuada pellentesque elit eget gravida. Nec ultrices dui sapien eget mi proin sed libero enim. Morbi tempus iaculis urna id volutpat lacus laoreet. Felis eget nunc lobortis mattis aliquam faucibus purus in massa. Vitae congue mauris rhoncus aenean. Egestas quis ipsum suspendisse ultrices gravida dictum. Quisque non tellus orci ac auctor augue mauris. Turpis nunc eget lorem dolor sed viverra ipsum nunc aliquet. Metus vulputate eu scelerisque felis imperdiet proin fermentum. Interdum varius sit amet mattis. At auctor urna nunc id. Dolor morbi non arcu risus quis varius quam quisque id. Cursus mattis molestie a iaculis. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Aenean pharetra magna ac placerat vestibulum lectus mauris. Nulla pellentesque dignissim enim sit. In nisl nisi scelerisque eu ultrices vitae auctor. Quisque id diam vel quam elementum pulvinar.

Nunc mi ipsum faucibus vitae aliquet. Ac ut consequat semper viverra nam libero justo laoreet. Urna neque viverra justo nec ultrices dui sapien. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Amet luctus venenatis lectus magna. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor. Elementum nibh tellus molestie nunc. Ac auctor augue mauris augue neque gravida. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Malesuada fames ac turpis egestas. Lorem sed risus ultricies tristique nulla. Tortor condimentum lacinia quis vel eros donec ac. Penatibus et magnis dis parturient montes nascetur ridiculus. Odio ut sem nulla pharetra diam sit amet. Mi proin sed libero enim sed faucibus turpis in eu. Tincidunt id aliquet risus feugiat in ante metus dictum. Vitae sapien pellentesque habitant morbi tristique senectus et netus et. A condimentum vitae sapien pellentesque. Arcu felis bibendum ut tristique et egestas. Vitae ultricies leo integer malesuada.

Non tellus orci ac auctor augue mauris. Lectus arcu bibendum at varius vel pharetra vel turpis. Potenti nullam ac tortor vitae purus faucibus ornare. Nulla pellentesque dignissim enim sit. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Sed viverra tellus in hac habitasse platea. Netus et malesuada fames ac turpis. Arcu vitae elementum curabitur vitae nunc sed. Est lorem ipsum dolor sit. Dui faucibus in ornare quam viverra orci sagittis eu volutpat. Auctor eu augue ut lectus arcu bibendum at.

Sollicitudin tempor id eu nisl nunc mi ipsum. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Imperdiet sed euismod nisi porta lorem mollis aliquam ut. Pharetra vel turpis nunc eget lorem dolor. Enim neque volutpat ac tincidunt vitae semper quis lectus. Ac odio tempor orci dapibus ultrices. Vitae justo eget magna fermentum iaculis. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Volutpat ac tincidunt vitae semper. Sit amet volutpat consequat mauris nunc congue nisi vitae. Eu ultrices vitae auctor eu augue ut. A erat nam at lectus urna. A pellentesque sit amet porttitor. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Velit euismod in pellentesque massa placerat duis. Integer feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Varius morbi enim nunc faucibus a pellentesque sit amet. Risus sed vulputate odio ut. Lectus nulla at volutpat diam ut venenatis tellus in metus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est velit.

Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Sit amet nisl purus in mollis nunc sed. Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Egestas tellus rutrum tellus pellentesque. Integer enim neque volutpat ac tincidunt vitae. Sed augue lacus viverra vitae congue eu consequat ac. Sollicitudin ac orci phasellus egestas tellus rutrum. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. Quam vulputate dignissim suspendisse in est ante in nibh mauris. Non diam phasellus vestibulum lorem sed. Risus sed vulputate odio ut.

Risus at ultrices mi tempus imperdiet. Id eu nisl nunc mi ipsum. Sit amet mattis vulputate enim nulla aliquet porttitor. Urna molestie at elementum eu facilisis sed odio morbi quis. Justo laoreet sit amet cursus sit. Cras tincidunt lobortis feugiat vivamus at augue. Magna ac placerat vestibulum lectus. Id neque aliquam vestibulum morbi. Egestas erat imperdiet sed euismod nisi porta lorem mollis. Elit eget gravida cum sociis natoque penatibus et. Tellus molestie nunc non blandit massa enim.

Mauris ultrices eros in cursus turpis. Consequat mauris nunc congue nisi vitae suscipit tellus. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Nunc vel risus commodo viverra maecenas accumsan. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque. Sed risus ultricies tristique nulla aliquet enim. Risus commodo viverra maecenas accumsan lacus. Nulla facilisi cras fermentum odio eu feugiat pretium. Scelerisque fermentum dui faucibus in ornare quam viverra. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Id porta nibh venenatis cras sed. Nunc eget lorem dolor sed viverra. Id venenatis a condimentum vitae sapien pellentesque habitant. Lectus nulla at volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta nibh venenatis cras. Tellus in hac habitasse platea. Vel quam elementum pulvinar etiam non quam lacus suspendisse.

At lectus urna duis convallis. Id volutpat lacus laoreet non curabitur gravida arcu ac. Id faucibus nisl tincidunt eget. Dolor morbi non arcu risus quis varius quam. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Diam ut venenatis tellus in metus vulputate eu scelerisque. Lacus laoreet non curabitur gravida arcu ac tortor dignissim convallis. Nunc id cursus metus aliquam eleifend. Diam quam nulla porttitor massa id neque aliquam vestibulum morbi. Turpis egestas pretium aenean pharetra magna. Ut aliquam purus sit amet luctus. Amet nisl suscipit adipiscing bibendum est ultricies. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Vitae ultricies leo integer malesuada nunc. Fusce ut placerat orci nulla pellentesque dignissim enim.

Quis commodo odio aenean sed adipiscing diam donec. Massa enim nec dui nunc mattis enim ut tellus elementum. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Aliquam ultrices sagittis orci a. Augue interdum velit euismod in pellentesque massa placerat duis ultricies. Aliquam id diam maecenas ultricies mi eget. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Suspendisse interdum consectetur libero id faucibus. In arcu cursus euismod quis viverra nibh cras. Nec dui nunc mattis enim. Lectus mauris ultrices eros in. Nunc non blandit massa enim nec dui. Ornare lectus sit amet est placerat in egestas erat. Metus aliquam eleifend mi in.

Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Et pharetra pharetra massa massa ultricies mi quis hendrerit dolor. Pellentesque massa placerat duis ultricies lacus. Adipiscing tristique risus nec feugiat in fermentum. Velit scelerisque in dictum non consectetur a erat nam. Odio tempor orci dapibus ultrices. Sit amet massa vitae tortor condimentum lacinia. Et ultrices neque ornare aenean euismod. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Ultrices eros in cursus turpis massa tincidunt dui ut. Neque aliquam vestibulum morbi blandit cursus risus at. Sem integer vitae justo eget magna fermentum iaculis eu non. Vitae tempus quam pellentesque nec nam. Ac ut consequat semper viverra nam libero justo laoreet sit.

Ipsum dolor sit amet consectetur adipiscing elit. Et molestie ac feugiat sed. Neque volutpat ac tincidunt vitae. Consequat semper viverra nam libero justo laoreet. Est sit amet facilisis magna etiam tempor orci. Fermentum leo vel orci porta non pulvinar neque laoreet. Fusce ut placerat orci nulla pellentesque dignissim enim sit amet. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Suspendisse sed nisi lacus sed viverra tellus in hac habitasse. Diam sit amet nisl suscipit adipiscing bibendum est ultricies. Id aliquet lectus proin nibh.

Faucibus interdum posuere lorem ipsum dolor. Lectus arcu bibendum at varius vel pharetra vel turpis nunc. Pharetra convallis posuere morbi leo urna molestie at. Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Dignissim suspendisse in est ante in nibh mauris. Vitae semper quis lectus nulla at volutpat diam ut venenatis. Enim diam vulputate ut pharetra sit amet aliquam id. Posuere morbi leo urna molestie. Sit amet nisl purus in mollis nunc sed id semper. Neque viverra justo nec ultrices dui sapien eget mi proin.

Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. Dolor magna eget est lorem ipsum dolor sit. Amet aliquam id diam maecenas ultricies mi eget. Augue ut lectus arcu bibendum at. Sapien nec sagittis aliquam malesuada bibendum arcu. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Sed elementum tempus egestas sed sed risus pretium quam vulputate. Cursus vitae congue mauris rhoncus aenean vel elit. Egestas integer eget aliquet nibh praesent tristique magna sit. Lobortis feugiat vivamus at augue. Est ante in nibh mauris cursus mattis molestie. At urna condimentum mattis pellentesque id. Sit amet tellus cras adipiscing enim eu turpis egestas.

Non quam lacus suspendisse faucibus interdum posuere. Diam vel quam elementum pulvinar etiam non quam. Tortor id aliquet lectus proin. Lacus vestibulum sed arcu non odio euismod lacinia. Lorem sed risus ultricies tristique nulla aliquet enim tortor. Aliquet sagittis id consectetur purus. Iaculis nunc sed augue lacus viverra vitae congue eu. Fringilla urna porttitor rhoncus dolor purus. Consectetur adipiscing elit duis tristique sollicitudin. Sapien eget mi proin sed. Integer enim neque volutpat ac tincidunt vitae. Hendrerit gravida rutrum quisque non tellus. Pellentesque dignissim enim sit amet venenatis. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Etiam sit amet nisl purus in mollis.

Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Magnis dis parturient montes nascetur ridiculus mus mauris vitae. Tellus orci ac auctor augue mauris augue neque. Purus ut faucibus pulvinar elementum integer enim. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Sagittis eu volutpat odio facilisis mauris sit amet massa. Feugiat in ante metus dictum at tempor. Amet facilisis magna etiam tempor orci eu. At elementum eu facilisis sed odio morbi quis commodo odio. Viverra accumsan in nisl nisi scelerisque eu ultrices. Volutpat ac tincidunt vitae semper quis lectus nulla. Varius quam quisque id diam. Non consectetur a erat nam at lectus urna. At risus viverra adipiscing at in tellus integer. Orci ac auctor augue mauris augue neque. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Justo donec enim diam vulputate. Mi quis hendrerit dolor magna eget est.

Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Vel quam elementum pulvinar etiam non quam lacus. At risus viverra adipiscing at in tellus integer feugiat scelerisque. Non blandit massa enim nec. Pharetra massa massa ultricies mi quis. Ipsum nunc aliquet bibendum enim facilisis gravida. Aliquam ultrices sagittis orci a scelerisque purus semper. Curabitur vitae nunc sed velit dignissim sodales ut. Orci a scelerisque purus semper eget duis. Quisque non tellus orci ac auctor augue. Sagittis purus sit amet volutpat. A lacus vestibulum sed arcu non odio euismod lacinia. Pretium nibh ipsum consequat nisl vel pretium. Sed arcu non odio euismod lacinia. Integer feugiat scelerisque varius morbi enim.

Ornare arcu odio ut sem nulla pharetra diam sit amet. Phasellus egestas tellus rutrum tellus pellentesque eu. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Sapien eget mi proin sed libero enim sed faucibus turpis. Facilisi etiam dignissim diam quis enim. Tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse. Molestie a iaculis at erat pellentesque adipiscing. Lacus sed viverra tellus in hac habitasse platea dictumst. Leo vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Integer vitae justo eget magna fermentum iaculis eu non. Ornare arcu dui vivamus arcu felis bibendum. Ac ut consequat semper viverra nam libero justo laoreet sit. Volutpat sed cras ornare arcu.

Donec ac odio tempor orci dapibus. Odio facilisis mauris sit amet massa. Ante metus dictum at tempor commodo ullamcorper. Ac tortor vitae purus faucibus. Amet dictum sit amet justo. Fringilla est ullamcorper eget nulla facilisi etiam dignissim. Convallis tellus id interdum velit. Donec enim diam vulputate ut pharetra sit. Non diam phasellus vestibulum lorem. Amet est placerat in egestas erat imperdiet sed. Tempor nec feugiat nisl pretium fusce id velit. Lobortis feugiat vivamus at augue eget arcu. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Fermentum posuere urna nec tincidunt praesent semper. Elementum nibh tellus molestie nunc non blandit massa enim.

Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Molestie nunc non blandit massa. Malesuada fames ac turpis egestas. Tincidunt augue interdum velit euismod in pellentesque massa placerat. Proin libero nunc consequat interdum varius sit. Curabitur vitae nunc sed velit dignissim sodales. Ipsum a arcu cursus vitae. A cras semper auctor neque vitae tempus quam. Sed sed risus pretium quam vulputate dignissim suspendisse. Amet risus nullam eget felis eget nunc lobortis. Netus et malesuada fames ac turpis egestas sed tempus urna. Mollis aliquam ut porttitor leo a diam sollicitudin tempor id. Arcu odio ut sem nulla. Nibh tortor id aliquet lectus proin. Quisque non tellus orci ac auctor augue mauris augue neque.

Aliquet enim tortor at auctor urna. Urna cursus eget nunc scelerisque viverra mauris in aliquam sem. Velit euismod in pellentesque massa placerat duis ultricies lacus. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices. Sem nulla pharetra diam sit amet nisl suscipit. Sed vulputate odio ut enim blandit volutpat maecenas. Eu augue ut lectus arcu bibendum at. Viverra accumsan in nisl nisi scelerisque eu ultrices vitae. Quisque id diam vel quam elementum. Enim blandit volutpat maecenas volutpat blandit aliquam. Tellus in hac habitasse platea dictumst vestibulum. Vitae turpis massa sed elementum. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Mauris commodo quis imperdiet massa tincidunt nunc. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Ut etiam sit amet nisl. Mauris pharetra et ultrices neque ornare aenean euismod elementum nisi. Augue neque gravida in fermentum et sollicitudin. Purus viverra accumsan in nisl nisi.


Say Hello`;
    const response = await callVertexAiApi(projectId, prompt);
    console.log(response);
    expect(response).toBeDefined();
  }, 40000);
  it.only('PROBLEMATIC OPEN HANDLE, Long prompt, Long response, should call and receive response from Vertex AI', async () => {
    const prompt = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel turpis nunc eget lorem dolor sed. Dolor sit amet consectetur adipiscing elit ut. Eget sit amet tellus cras adipiscing enim eu turpis egestas. Aliquet nec ullamcorper sit amet risus. Id semper risus in hendrerit gravida rutrum quisque non tellus. Nisl suscipit adipiscing bibendum est ultricies integer. Accumsan in nisl nisi scelerisque eu ultrices vitae. Sit amet nisl suscipit adipiscing bibendum est ultricies integer quis. Etiam tempor orci eu lobortis elementum nibh. Aenean euismod elementum nisi quis eleifend.

Potenti nullam ac tortor vitae. Vel pretium lectus quam id. Adipiscing tristique risus nec feugiat. Adipiscing diam donec adipiscing tristique risus nec feugiat in. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Feugiat vivamus at augue eget arcu dictum. Tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque. In aliquam sem fringilla ut morbi tincidunt augue. Porta nibh venenatis cras sed felis. Aliquam malesuada bibendum arcu vitae. A cras semper auctor neque vitae tempus quam. Sit amet dictum sit amet justo donec enim diam vulputate. Volutpat sed cras ornare arcu dui vivamus arcu. Sed odio morbi quis commodo odio aenean sed.

Neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Sit amet aliquam id diam maecenas ultricies. Volutpat maecenas volutpat blandit aliquam. In pellentesque massa placerat duis ultricies lacus sed turpis. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Aliquam purus sit amet luctus venenatis. Enim tortor at auctor urna nunc. Elementum sagittis vitae et leo duis ut. Lacus vestibulum sed arcu non odio euismod lacinia at. Quam vulputate dignissim suspendisse in est. Magnis dis parturient montes nascetur. Quis imperdiet massa tincidunt nunc pulvinar.

Adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Malesuada pellentesque elit eget gravida. Nec ultrices dui sapien eget mi proin sed libero enim. Morbi tempus iaculis urna id volutpat lacus laoreet. Felis eget nunc lobortis mattis aliquam faucibus purus in massa. Vitae congue mauris rhoncus aenean. Egestas quis ipsum suspendisse ultrices gravida dictum. Quisque non tellus orci ac auctor augue mauris. Turpis nunc eget lorem dolor sed viverra ipsum nunc aliquet. Metus vulputate eu scelerisque felis imperdiet proin fermentum. Interdum varius sit amet mattis. At auctor urna nunc id. Dolor morbi non arcu risus quis varius quam quisque id. Cursus mattis molestie a iaculis. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Aenean pharetra magna ac placerat vestibulum lectus mauris. Nulla pellentesque dignissim enim sit. In nisl nisi scelerisque eu ultrices vitae auctor. Quisque id diam vel quam elementum pulvinar.

Nunc mi ipsum faucibus vitae aliquet. Ac ut consequat semper viverra nam libero justo laoreet. Urna neque viverra justo nec ultrices dui sapien. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Amet luctus venenatis lectus magna. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor. Elementum nibh tellus molestie nunc. Ac auctor augue mauris augue neque gravida. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Malesuada fames ac turpis egestas. Lorem sed risus ultricies tristique nulla. Tortor condimentum lacinia quis vel eros donec ac. Penatibus et magnis dis parturient montes nascetur ridiculus. Odio ut sem nulla pharetra diam sit amet. Mi proin sed libero enim sed faucibus turpis in eu. Tincidunt id aliquet risus feugiat in ante metus dictum. Vitae sapien pellentesque habitant morbi tristique senectus et netus et. A condimentum vitae sapien pellentesque. Arcu felis bibendum ut tristique et egestas. Vitae ultricies leo integer malesuada.

Non tellus orci ac auctor augue mauris. Lectus arcu bibendum at varius vel pharetra vel turpis. Potenti nullam ac tortor vitae purus faucibus ornare. Nulla pellentesque dignissim enim sit. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Sed viverra tellus in hac habitasse platea. Netus et malesuada fames ac turpis. Arcu vitae elementum curabitur vitae nunc sed. Est lorem ipsum dolor sit. Dui faucibus in ornare quam viverra orci sagittis eu volutpat. Auctor eu augue ut lectus arcu bibendum at.

Sollicitudin tempor id eu nisl nunc mi ipsum. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Imperdiet sed euismod nisi porta lorem mollis aliquam ut. Pharetra vel turpis nunc eget lorem dolor. Enim neque volutpat ac tincidunt vitae semper quis lectus. Ac odio tempor orci dapibus ultrices. Vitae justo eget magna fermentum iaculis. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Volutpat ac tincidunt vitae semper. Sit amet volutpat consequat mauris nunc congue nisi vitae. Eu ultrices vitae auctor eu augue ut. A erat nam at lectus urna. A pellentesque sit amet porttitor. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Velit euismod in pellentesque massa placerat duis. Integer feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Varius morbi enim nunc faucibus a pellentesque sit amet. Risus sed vulputate odio ut. Lectus nulla at volutpat diam ut venenatis tellus in metus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est velit.

Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Sit amet nisl purus in mollis nunc sed. Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Egestas tellus rutrum tellus pellentesque. Integer enim neque volutpat ac tincidunt vitae. Sed augue lacus viverra vitae congue eu consequat ac. Sollicitudin ac orci phasellus egestas tellus rutrum. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. Quam vulputate dignissim suspendisse in est ante in nibh mauris. Non diam phasellus vestibulum lorem sed. Risus sed vulputate odio ut.

Risus at ultrices mi tempus imperdiet. Id eu nisl nunc mi ipsum. Sit amet mattis vulputate enim nulla aliquet porttitor. Urna molestie at elementum eu facilisis sed odio morbi quis. Justo laoreet sit amet cursus sit. Cras tincidunt lobortis feugiat vivamus at augue. Magna ac placerat vestibulum lectus. Id neque aliquam vestibulum morbi. Egestas erat imperdiet sed euismod nisi porta lorem mollis. Elit eget gravida cum sociis natoque penatibus et. Tellus molestie nunc non blandit massa enim.

Mauris ultrices eros in cursus turpis. Consequat mauris nunc congue nisi vitae suscipit tellus. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Nunc vel risus commodo viverra maecenas accumsan. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque. Sed risus ultricies tristique nulla aliquet enim. Risus commodo viverra maecenas accumsan lacus. Nulla facilisi cras fermentum odio eu feugiat pretium. Scelerisque fermentum dui faucibus in ornare quam viverra. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Id porta nibh venenatis cras sed. Nunc eget lorem dolor sed viverra. Id venenatis a condimentum vitae sapien pellentesque habitant. Lectus nulla at volutpat diam ut venenatis tellus in metus. Sem et tortor consequat id porta nibh venenatis cras. Tellus in hac habitasse platea. Vel quam elementum pulvinar etiam non quam lacus suspendisse.

At lectus urna duis convallis. Id volutpat lacus laoreet non curabitur gravida arcu ac. Id faucibus nisl tincidunt eget. Dolor morbi non arcu risus quis varius quam. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Diam ut venenatis tellus in metus vulputate eu scelerisque. Lacus laoreet non curabitur gravida arcu ac tortor dignissim convallis. Nunc id cursus metus aliquam eleifend. Diam quam nulla porttitor massa id neque aliquam vestibulum morbi. Turpis egestas pretium aenean pharetra magna. Ut aliquam purus sit amet luctus. Amet nisl suscipit adipiscing bibendum est ultricies. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Vitae ultricies leo integer malesuada nunc. Fusce ut placerat orci nulla pellentesque dignissim enim.

Quis commodo odio aenean sed adipiscing diam donec. Massa enim nec dui nunc mattis enim ut tellus elementum. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Aliquam ultrices sagittis orci a. Augue interdum velit euismod in pellentesque massa placerat duis ultricies. Aliquam id diam maecenas ultricies mi eget. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Suspendisse interdum consectetur libero id faucibus. In arcu cursus euismod quis viverra nibh cras. Nec dui nunc mattis enim. Lectus mauris ultrices eros in. Nunc non blandit massa enim nec dui. Ornare lectus sit amet est placerat in egestas erat. Metus aliquam eleifend mi in.

Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Et pharetra pharetra massa massa ultricies mi quis hendrerit dolor. Pellentesque massa placerat duis ultricies lacus. Adipiscing tristique risus nec feugiat in fermentum. Velit scelerisque in dictum non consectetur a erat nam. Odio tempor orci dapibus ultrices. Sit amet massa vitae tortor condimentum lacinia. Et ultrices neque ornare aenean euismod. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Ultrices eros in cursus turpis massa tincidunt dui ut. Neque aliquam vestibulum morbi blandit cursus risus at. Sem integer vitae justo eget magna fermentum iaculis eu non. Vitae tempus quam pellentesque nec nam. Ac ut consequat semper viverra nam libero justo laoreet sit.

Ipsum dolor sit amet consectetur adipiscing elit. Et molestie ac feugiat sed. Neque volutpat ac tincidunt vitae. Consequat semper viverra nam libero justo laoreet. Est sit amet facilisis magna etiam tempor orci. Fermentum leo vel orci porta non pulvinar neque laoreet. Fusce ut placerat orci nulla pellentesque dignissim enim sit amet. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Suspendisse sed nisi lacus sed viverra tellus in hac habitasse. Diam sit amet nisl suscipit adipiscing bibendum est ultricies. Id aliquet lectus proin nibh.

Faucibus interdum posuere lorem ipsum dolor. Lectus arcu bibendum at varius vel pharetra vel turpis nunc. Pharetra convallis posuere morbi leo urna molestie at. Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Dignissim suspendisse in est ante in nibh mauris. Vitae semper quis lectus nulla at volutpat diam ut venenatis. Enim diam vulputate ut pharetra sit amet aliquam id. Posuere morbi leo urna molestie. Sit amet nisl purus in mollis nunc sed id semper. Neque viverra justo nec ultrices dui sapien eget mi proin.

Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. Dolor magna eget est lorem ipsum dolor sit. Amet aliquam id diam maecenas ultricies mi eget. Augue ut lectus arcu bibendum at. Sapien nec sagittis aliquam malesuada bibendum arcu. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Sed elementum tempus egestas sed sed risus pretium quam vulputate. Cursus vitae congue mauris rhoncus aenean vel elit. Egestas integer eget aliquet nibh praesent tristique magna sit. Lobortis feugiat vivamus at augue. Est ante in nibh mauris cursus mattis molestie. At urna condimentum mattis pellentesque id. Sit amet tellus cras adipiscing enim eu turpis egestas.

Non quam lacus suspendisse faucibus interdum posuere. Diam vel quam elementum pulvinar etiam non quam. Tortor id aliquet lectus proin. Lacus vestibulum sed arcu non odio euismod lacinia. Lorem sed risus ultricies tristique nulla aliquet enim tortor. Aliquet sagittis id consectetur purus. Iaculis nunc sed augue lacus viverra vitae congue eu. Fringilla urna porttitor rhoncus dolor purus. Consectetur adipiscing elit duis tristique sollicitudin. Sapien eget mi proin sed. Integer enim neque volutpat ac tincidunt vitae. Hendrerit gravida rutrum quisque non tellus. Pellentesque dignissim enim sit amet venenatis. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Etiam sit amet nisl purus in mollis.

Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Magnis dis parturient montes nascetur ridiculus mus mauris vitae. Tellus orci ac auctor augue mauris augue neque. Purus ut faucibus pulvinar elementum integer enim. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Sagittis eu volutpat odio facilisis mauris sit amet massa. Feugiat in ante metus dictum at tempor. Amet facilisis magna etiam tempor orci eu. At elementum eu facilisis sed odio morbi quis commodo odio. Viverra accumsan in nisl nisi scelerisque eu ultrices. Volutpat ac tincidunt vitae semper quis lectus nulla. Varius quam quisque id diam. Non consectetur a erat nam at lectus urna. At risus viverra adipiscing at in tellus integer. Orci ac auctor augue mauris augue neque. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Justo donec enim diam vulputate. Mi quis hendrerit dolor magna eget est.

Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Vel quam elementum pulvinar etiam non quam lacus. At risus viverra adipiscing at in tellus integer feugiat scelerisque. Non blandit massa enim nec. Pharetra massa massa ultricies mi quis. Ipsum nunc aliquet bibendum enim facilisis gravida. Aliquam ultrices sagittis orci a scelerisque purus semper. Curabitur vitae nunc sed velit dignissim sodales ut. Orci a scelerisque purus semper eget duis. Quisque non tellus orci ac auctor augue. Sagittis purus sit amet volutpat. A lacus vestibulum sed arcu non odio euismod lacinia. Pretium nibh ipsum consequat nisl vel pretium. Sed arcu non odio euismod lacinia. Integer feugiat scelerisque varius morbi enim.

Ornare arcu odio ut sem nulla pharetra diam sit amet. Phasellus egestas tellus rutrum tellus pellentesque eu. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Sapien eget mi proin sed libero enim sed faucibus turpis. Facilisi etiam dignissim diam quis enim. Tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse. Molestie a iaculis at erat pellentesque adipiscing. Lacus sed viverra tellus in hac habitasse platea dictumst. Leo vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Integer vitae justo eget magna fermentum iaculis eu non. Ornare arcu dui vivamus arcu felis bibendum. Ac ut consequat semper viverra nam libero justo laoreet sit. Volutpat sed cras ornare arcu.

Donec ac odio tempor orci dapibus. Odio facilisis mauris sit amet massa. Ante metus dictum at tempor commodo ullamcorper. Ac tortor vitae purus faucibus. Amet dictum sit amet justo. Fringilla est ullamcorper eget nulla facilisi etiam dignissim. Convallis tellus id interdum velit. Donec enim diam vulputate ut pharetra sit. Non diam phasellus vestibulum lorem. Amet est placerat in egestas erat imperdiet sed. Tempor nec feugiat nisl pretium fusce id velit. Lobortis feugiat vivamus at augue eget arcu. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Fermentum posuere urna nec tincidunt praesent semper. Elementum nibh tellus molestie nunc non blandit massa enim.

Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Molestie nunc non blandit massa. Malesuada fames ac turpis egestas. Tincidunt augue interdum velit euismod in pellentesque massa placerat. Proin libero nunc consequat interdum varius sit. Curabitur vitae nunc sed velit dignissim sodales. Ipsum a arcu cursus vitae. A cras semper auctor neque vitae tempus quam. Sed sed risus pretium quam vulputate dignissim suspendisse. Amet risus nullam eget felis eget nunc lobortis. Netus et malesuada fames ac turpis egestas sed tempus urna. Mollis aliquam ut porttitor leo a diam sollicitudin tempor id. Arcu odio ut sem nulla. Nibh tortor id aliquet lectus proin. Quisque non tellus orci ac auctor augue mauris augue neque.

Aliquet enim tortor at auctor urna. Urna cursus eget nunc scelerisque viverra mauris in aliquam sem. Velit euismod in pellentesque massa placerat duis ultricies lacus. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices. Sem nulla pharetra diam sit amet nisl suscipit. Sed vulputate odio ut enim blandit volutpat maecenas. Eu augue ut lectus arcu bibendum at. Viverra accumsan in nisl nisi scelerisque eu ultrices vitae. Quisque id diam vel quam elementum. Enim blandit volutpat maecenas volutpat blandit aliquam. Tellus in hac habitasse platea dictumst vestibulum. Vitae turpis massa sed elementum. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Mauris commodo quis imperdiet massa tincidunt nunc. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Ut etiam sit amet nisl. Mauris pharetra et ultrices neque ornare aenean euismod elementum nisi. Augue neque gravida in fermentum et sollicitudin. Purus viverra accumsan in nisl nisi.

ANSWER ME WITH A LONG RESPONSE, SIMILAR LENGTH TO THE PROMPT`;
    const response = await callVertexAiApi(projectId, prompt);
    console.log(response);
    expect(response).toBeDefined();
  }, 40000);
});
